[package]
name = "tspam"
version = "0.1.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "~0.99"
env_logger = "~0.6"
futures-preview = "~0.3.0-alpha.18"
log = "~0.4"
structopt = "~0.3"
